### PR TITLE
interests

### PR DESCRIPTION
**Pull request by JAIRUS-TEYIE**
giving brief intro to yourself

### CODE REVIEW

**Comment by JanjaProgrammers** [comment]
Dear Jairus,

I am delighted to inform you that you have successfully passed Project One!
Your dedication and hard work have paid off, and I commend you on your
achievement.

Your project demonstrated a solid understanding of the concepts covered,
and you effectively implemented the required functionalities. Your
commitment to excellence is evident, and I am confident that you will
continue to excel in future projects.

Keep up the fantastic work, and congratulations once again on this
accomplishment. If you have any questions or need further guidance, please
don't hesitate to reach out.



*Best regards,Kalutu Daniel,Janja Programmers.*

**Comment by JAIRUS-TEYIE** [comment]
Thanks for the great news on my end. Rank you guys!

**Comment by JanjaProgrammers** [comment]
Feel most welcomed. You are now a contributor to the repo

**Comment by JanjaProgrammers** [comment]
Congratulations! You are now a contributor.

**Pull request merged**
